version: '3.8'

services:
  frontend:
    build:
      context: ./qr-test-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./qr-test-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./qr-test-backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
